### ISSUE TITLE
talao.co/emailpass plante

### ISSUE THREAD

**Issue by thierry-thevenet** [TalaoDAO/credible#1]
le emailpass sur Talao.co/emailpass plante parceque il n y a pas de key "proof" dans les data envoyées avec le GET alors que sur la base de test ils ont tous un "proof". Mais en fait dans le GET du credentialOffer le credential n est pas encore signé donc il est normal que le "proof"  n'existe pas...... C 'est la base de test qui est imparfaire parcequ'elle recycle des credentials dejà signés.....

**Comment by ThierryThevenet** [comment]
meme issue que #2
