### ISSUE TITLE
change color of VC credential and app background

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/credible#10]
Choisir une palette de couleurs pour les VCs qui soit plus proche de celle de nos concurrents, peut être un fond de l'app en gris ? et le  VC de ResidentCard en blanc.

**Comment by ThierryThevenet** [comment]
peut etre voi run code couleur par nature :
Col 1 :  gouvernement  (ResidentCard, CitizenVC, DrivberLicense, Pass sanitaire....
Col 2 : entreprise comme employeur (Skill, Experience, IdentityPass, Attestation employeur...
Col 3 : general and social media (PhonePass,  EmailPass, ...
Col 4....
Col 5 : default

**Comment by hawkbee1** [comment]
pour info, couleur de fond de l'app myguichet.lu : #efefef
