### ISSUE TITLE
signature missing in professional student card

### ISSUE THREAD

**Issue by bibash28** [TalaoDAO/credible#144]
app/shared/model/professional_student_card/professional_student_card.dart

Line 135
                  LayoutId(
                    id: 'signature',
                    child: ImageCardText(text: 'missing field'),
                  ),

![Screenshot_20220210-082335.jpg](https://user-images.githubusercontent.com/18188709/153339911-9e422b91-0d17-4001-86cf-b6bf552b9abd.jpg)

**Comment by hawkbee1** [comment]
That's currently the expected behavior
