### ISSUE TITLE
Test build 48

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/credible#175]
1) when one deletes a credential the message (bottom of the screen) is RED instead of green

2) Personal screen : the icon "key" is not meaningfull, best woud be to replace by teh ID card icon which is used on the self issued crerdential within the credetila list screen 

3) self issued  credential : the firstname and lastname label are mixed (not the same as the screen of personal screen)

4) self issued credential : the green spinner does not work properly on IOS and is not v!sible on Android. 

5) return code for test Test 3 : the app is waiting for the process wich should be stoppped after receiving and error code.

**Comment by hawkbee1** [comment]
split into 5 tickets:
#176 
#177
#178 
#179 
#180
