### ISSUE TITLE
self issued: first name and last name inversion

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/credible#178]
self issued credential : the firstname and lastname label are mixed (not the same as the screen of personal screen)

**Comment by TalebRafiepour** [comment]
@hawkbee1 
Do you mean where we display self-issued credential cards???
Or Where?

**Comment by hawkbee1** [comment]
Yes, when we display the self issued credential.
![Screenshot_20220228-104536](https://user-images.githubusercontent.com/49282360/155962126-1666befa-0b44-4185-90ef-b80e1abe771a.png)
![Screenshot_20220228-104515](https://user-images.githubusercontent.com/49282360/155962128-f1ee7331-db15-4552-b0a6-0cfdb0ee741f.png)

**Comment by TalebRafiepour** [comment]
thanks,
fixed
