### ISSUE TITLE
self issued credential : the green spinner does not work properly on IOS and is not v!sible on Android.

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/credible#179]
@TalebRafiepour should I test it on my iphone to provide more information?

**Comment by TalebRafiepour** [comment]
@hawkbee1 Yes Please
Because I can't test it on iphone

**Comment by TalebRafiepour** [comment]
I think huge processing freeze the UI
For solving the problem should we use Isolate when creating self-issued credential

**Comment by hawkbee1** [comment]
Normally  that's the spinner during SelfIssued creation from personal page: 
``` dart
Builder(builder: (_) {
            return state.maybeWhen(
                orElse: () => Icon(Icons.vpn_key),
                loading: () => Center(child: CircularProgressIndicator()));
          }),
```

**Comment by hawkbee1** [comment]
SelfIssued creation is already an isolate according to me (use of Future).
