### ISSUE TITLE
After wallet reset no DID are showing in global information

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/credible#186]
Looks like the key is weird:

      final key = (await secureStorageProvider!.get('key'))!;  ///. => key: 864263246
      final DID = didKitProvider!.keyToDID(Constants.defaultDIDMethod, key);

**Comment by hawkbee1** [comment]
Apparently that's just in the backup&recovery branch

**Comment by bibash28** [comment]
I did some mistake while generating keypair... I will recover it..
