### ISSUE TITLE
Enter DID and submit private key

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/credible#188]
As an Enterprise user I write my enterprise DID (“did:web:xxxx”). The textField already contain did:web: since all enterprise DID will start with this string.

Import json file containing private RSA key through a "+" Icon

User submit by pressing button.
After submitting we check the DID and RSA key. If that's OK we store those information and process to the personnal information screen.
Checking process is in #189 
If check is falling a message is displayed to user.

**Comment by hawkbee1** [comment]
Here's the private key we will use for testing:
```
{
    "d": "BLn1w1y3xDp0a-8E97nk54e-FHZE8bNjqugAvAupgSKG4-l26l2UibXTw7FKTb_ZE9ok8aAUUppMar-LMrZCIU9fqUDffzao8EIGfddfr4HR00pVZ84-c0nT9n9As0jcfwgI3Xc84tgVkRgGQpIkD5wYVXGTXhvmj6lzDNj8DPDimcuRs6bHmaTZeCWBWA4LYhmf7hHxwP7BEMygUmwvQnbitmA-3hS75rYn4cwWJvju07CDEM2jpMcF6Oolyl6Ie3R9kVfv7QYE4F81m1Ig87KGOGlXqMEQ5Zdvtl2b5aGl5J2mGRmS9PF-eDBw2mImBi9EI0F9Wj967iJ8Dd0HxQ",
    "dp": "dMXKqre0YGto7ut_b4_b_SXnnaCbVOQHQUiCtmqJtANqZ50vmsFpaVxXs_WX4tGBpx2xaOy9-C4gcjm4sn5W-eZ2HcCI827OD3eKObRJVsW7gnQKaBYs4NPyJW4omCUqcNejNfqsefVSefgqbVfmq_zCXrUBxLQmWATZP1m7KLU",
    "dq": "Y2eTt3Jl1LzHQYo3rpDPsEPgU0pdZ0XRttOKamfENh8sWjNp2MKePJhGH-053L98IoUuB7AKaJHhbf64dSCjpKkjXZ2R48AMdI7y_Fvs7Ied-GGVyv_RuTQifgYQqh6iiJ5oVJna-HUGhsIdt2IrQvV534KN_HXfNV34XS_HZk0",
    "e": "AQAB",
    "kid": "did:web:ecole42.talao.co#key-1",
    "kty": "RSA",
    "n": "ilResnUjv6kwJW8yh9u3kS3_2hWYtHD-hN0tBUaSe6UdhGYvmLUxRzyssEs5ib_JjChyhrvFbgWpSmRQK5wQEgGnhxs1isdXXNsEIQY0hKxwR1s5b2WxHsGi65bYMOFr_s2ZkNTpWDnlGNjpvw16Cnp94Ak9GUSHMf1HzQP2C5ou6l6k9Iz4CHpYZCPuM5kaerFDfN-TyQRVnek6vN7rFXbtgaBGzwDVl1aQa75jd5osmMy_43brnQsl2bFwoJLxzzye9V-nBKqZWsMi2V6tB_loYUhBTtxlKyY53R9QoNtJTwx25KMjHIpDCrPoSDXyYV_JfjW9iNGZenNbpoLS6Q",
    "p": "up2lOWo2Bg3N79wIYlP1kZs84WggC8gq7oz4BYa1ViXOsL-dqtIcuHC4x-TbQ-ihgru3Wm-_NVFs3Z-YmZw3T3H4UrFROKynHUGZ0Ui5y_5w7bZ7F06X3-TATbV9QiAqSXZtaq2LlKomL_i8dX-9tB_tMbSUqGkX5Cc8aQSamvU",
    "q": "vcLF4bnmiTXBkurxj9449pQr3qSySjCFe1pCVd_C5eObpDhBLINhs2hJ-R62iu442c77pOxHBfXMj9uoqiSWwbgSXUMOMz4nc3qy0wFBPjsuWBduPQ20HLUrJ15i1YNmxZFkhJk4MH_FvugiX0hIo0esdg887ByScjt5O-53R6U",
    "qi": "gQ5rYsAmPivde03lz9-KdZ2Krad5zeP4NrMrHtjrVfhykyn412OBmVfCAmdMHloBPJTg-23cg--JiQ_c0lqgQfwjQjp6BB6K4q109jpATbTtmGKcJUpBkHdoBcYbpcP87qNhvu9YRUcwEGoJHs02HWy7mG9maIxOAXwU3SoaU_A"
}
```

**Comment by hawkbee1** [comment]
Limit the file size to prevent application crash

**Comment by hawkbee1** [comment]
complexity: 3

**Comment by hawkbee1** [comment]
information from Bibash: We have almost everything, including tests, in the backup & recovery part.

**Comment by hawkbee1** [comment]
[demo.talo.key.private.txt](https://github.com/TalaoDAO/talao-wallet/files/8287374/demo.talo.key.private.txt)

**Comment by TalebRafiepour** [comment]
@hawkbee1 
Not found anything inside link

**Comment by hawkbee1** [comment]
file sharing not working as expected. That's just a file containing

{
    "d": "BLn1w1y3xDp0a-8E97nk54e-FHZE8bNjqugAvAupgSKG4-l26l2UibXTw7FKTb_ZE9ok8aAUUppMar-LMrZCIU9fqUDffzao8EIGfddfr4HR00pVZ84-c0nT9n9As0jcfwgI3Xc84tgVkRgGQpIkD5wYVXGTXhvmj6lzDNj8DPDimcuRs6bHmaTZeCWBWA4LYhmf7hHxwP7BEMygUmwvQnbitmA-3hS75rYn4cwWJvju07CDEM2jpMcF6Oolyl6Ie3R9kVfv7QYE4F81m1Ig87KGOGlXqMEQ5Zdvtl2b5aGl5J2mGRmS9PF-eDBw2mImBi9EI0F9Wj967iJ8Dd0HxQ",
    "dp": "dMXKqre0YGto7ut_b4_b_SXnnaCbVOQHQUiCtmqJtANqZ50vmsFpaVxXs_WX4tGBpx2xaOy9-C4gcjm4sn5W-eZ2HcCI827OD3eKObRJVsW7gnQKaBYs4NPyJW4omCUqcNejNfqsefVSefgqbVfmq_zCXrUBxLQmWATZP1m7KLU",
    "dq": "Y2eTt3Jl1LzHQYo3rpDPsEPgU0pdZ0XRttOKamfENh8sWjNp2MKePJhGH-053L98IoUuB7AKaJHhbf64dSCjpKkjXZ2R48AMdI7y_Fvs7Ied-GGVyv_RuTQifgYQqh6iiJ5oVJna-HUGhsIdt2IrQvV534KN_HXfNV34XS_HZk0",
    "e": "AQAB",
    "kid": "did:web:demo.talao.co#key-1",
    "kty": "RSA",
    "n": "ilResnUjv6kwJW8yh9u3kS3_2hWYtHD-hN0tBUaSe6UdhGYvmLUxRzyssEs5ib_JjChyhrvFbgWpSmRQK5wQEgGnhxs1isdXXNsEIQY0hKxwR1s5b2WxHsGi65bYMOFr_s2ZkNTpWDnlGNjpvw16Cnp94Ak9GUSHMf1HzQP2C5ou6l6k9Iz4CHpYZCPuM5kaerFDfN-TyQRVnek6vN7rFXbtgaBGzwDVl1aQa75jd5osmMy_43brnQsl2bFwoJLxzzye9V-nBKqZWsMi2V6tB_loYUhBTtxlKyY53R9QoNtJTwx25KMjHIpDCrPoSDXyYV_JfjW9iNGZenNbpoLS6Q",
    "p": "up2lOWo2Bg3N79wIYlP1kZs84WggC8gq7oz4BYa1ViXOsL-dqtIcuHC4x-TbQ-ihgru3Wm-_NVFs3Z-YmZw3T3H4UrFROKynHUGZ0Ui5y_5w7bZ7F06X3-TATbV9QiAqSXZtaq2LlKomL_i8dX-9tB_tMbSUqGkX5Cc8aQSamvU",
    "q": "vcLF4bnmiTXBkurxj9449pQr3qSySjCFe1pCVd_C5eObpDhBLINhs2hJ-R62iu442c77pOxHBfXMj9uoqiSWwbgSXUMOMz4nc3qy0wFBPjsuWBduPQ20HLUrJ15i1YNmxZFkhJk4MH_FvugiX0hIo0esdg887ByScjt5O-53R6U",
    "qi": "gQ5rYsAmPivde03lz9-KdZ2Krad5zeP4NrMrHtjrVfhykyn412OBmVfCAmdMHloBPJTg-23cg--JiQ_c0lqgQfwjQjp6BB6K4q109jpATbTtmGKcJUpBkHdoBcYbpcP87qNhvu9YRUcwEGoJHs02HWy7mG9maIxOAXwU3SoaU_A"
}
