### ISSUE TITLE
DID storage

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/credible#194]
Currently DID:tz is computed from key by didKit every time we need it: 
final did = DIDKitProvider.instance.keyToDID(Constants.defaultDIDMethod, key);

In case of Enterprise onBoarding the DID is given by user. So this DID needs to be stored.
Warning, it has consequences on the Global information page since we display the DID.

**Comment by TalebRafiepour** [comment]
@hawkbee1 
Can you explain more?
Do we need to save "did" provided by enterprise users in "secure-storage"?
If so, we just need to call "secureStorage.write('did',didValue)"  , right ? Or more work we need?

**Comment by hawkbee1** [comment]
Yes we store the DID in secure storage.
When we generate key for non enterprise user we will also store the DID (result of keyToDid)
