### ISSUE TITLE
1/ get instructions from SiopV2 presentation request 

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/credible#200]
![image](https://user-images.githubusercontent.com/49282360/157081412-b321a56b-794d-4d91-96ee-3da3907cb6ef.png)

**Comment by hawkbee1** [comment]
OpenId request occurs when the content of the QR code use openid protocol.

```
openid://?scope=openid&response_type=id_token&client_id=did:web:talao.co&redirect_uri=https://talao.co/siopv2/verifier_redirect/dd4c2c2a-9df3-11ec-a647-0a4a9675ed9a&response_mode=post&claims={'vp_token':+{'presentation_definition':+{'id':+'emailpass_for_gaiax',+'input_descriptors':+[{'id':+'EmailPass+issued+by+Talao',+'purpose':+'Test+for+GAIA-X+project',+'format':+{'ldp_vc':+{'proof_type':+['Ed25519Signature2018',+'JsonWebSignature2020']}},+'constraints':+{'limit_disclosure':+'required',+'fields':+[{'path':+['$.credentialSubject.type'],+'purpose':+'One+can+only+accept+EmailPass',+'filter':+{'type':+'string',+'pattern':+'EmailPass'}},+{'path':+['$.issuer'],+'purpose':+'One+can+accept+only+EmailPass+signed+by+Talao',+'filter':+{'type':+'string',+'pattern':+'did:web:talao.co'}}]}}]}}}&nonce=8lONH5O_05&registration={'subject_syntax_types_supported':+['urn:ietf:params:oauth:jwk-thumbprint',+'did:key',+'did:web',+'did:ethr',+'did:tz']}&request_uri=https://talao.co/siopv2/verifier_request_uri/dd4c2c2a-9df3-11ec-a647-0a4a9675ed9a
```

**Comment by hawkbee1** [comment]
complexity: 5

**Comment by hawkbee1** [comment]
request_uri from example is https://talao.co/siopv2/verifier_request_uri/dd4c2c2a-9df3-11ec-a647-0a4a9675ed9a

content of the file is 
"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImRpZDp3ZWI6dGFsYW8uY28ja2V5LTIifQ.eyJzY29wZSI6Im9wZW5pZCIsInJlc3BvbnNlX3R5cGUiOiJpZF90b2tlbiIsImNsaWVudF9pZCI6ImRpZDp3ZWI6dGFsYW8uY28iLCJyZWRpcmVjdF91cmkiOiJodHRwczovL3RhbGFvLmNvL3Npb3B2Mi92ZXJpZmllcl9yZWRpcmVjdC9kZDRjMmMyYS05ZGYzLTExZWMtYTY0Ny0wYTRhOTY3NWVkOWEiLCJyZXNwb25zZV9tb2RlIjoicG9zdCIsImNsYWltcyI6eyJ2cF90b2tlbiI6eyJwcmVzZW50YXRpb25fZGVmaW5pdGlvbiI6eyJpZCI6ImVtYWlscGFzc19mb3JfZ2FpYXgiLCJpbnB1dF9kZXNjcmlwdG9ycyI6W3siaWQiOiJFbWFpbFBhc3MgaXNzdWVkIGJ5IFRhbGFvIiwicHVycG9zZSI6IlRlc3QgZm9yIEdBSUEtWCBwcm9qZWN0IiwiZm9ybWF0Ijp7ImxkcF92YyI6eyJwcm9vZl90eXBlIjpbIkVkMjU1MTlTaWduYXR1cmUyMDE4IiwiSnNvbldlYlNpZ25hdHVyZTIwMjAiXX19LCJjb25zdHJhaW50cyI6eyJsaW1pdF9kaXNjbG9zdXJlIjoicmVxdWlyZWQiLCJmaWVsZHMiOlt7InBhdGgiOlsiJC5jcmVkZW50aWFsU3ViamVjdC50eXBlIl0sInB1cnBvc2UiOiJPbmUgY2FuIG9ubHkgYWNjZXB0IEVtYWlsUGFzcyIsImZpbHRlciI6eyJ0eXBlIjoic3RyaW5nIiwicGF0dGVybiI6IkVtYWlsUGFzcyJ9fSx7InBhdGgiOlsiJC5pc3N1ZXIiXSwicHVycG9zZSI6Ik9uZSBjYW4gYWNjZXB0IG9ubHkgRW1haWxQYXNzIHNpZ25lZCBieSBUYWxhbyIsImZpbHRlciI6eyJ0eXBlIjoic3RyaW5nIiwicGF0dGVybiI6ImRpZDp3ZWI6dGFsYW8uY28ifX1dfX1dfX19LCJub25jZSI6IjhsT05INU9fMDUiLCJyZWdpc3RyYXRpb24iOnsic3ViamVjdF9zeW50YXhfdHlwZXNfc3VwcG9ydGVkIjpbInVybjppZXRmOnBhcmFtczpvYXV0aDpqd2stdGh1bWJwcmludCIsImRpZDprZXkiLCJkaWQ6d2ViIiwiZGlkOmV0aHIiLCJkaWQ6dHoiXX0sInJlcXVlc3RfdXJpIjoiaHR0cHM6Ly90YWxhby5jby9zaW9wdjIvdmVyaWZpZXJfcmVxdWVzdF91cmkvZGQ0YzJjMmEtOWRmMy0xMWVjLWE2NDctMGE0YTk2NzVlZDlhIn0.GgXjfOcakwJbAqunUb-50Re0mfdRP_wWeN3FuCVrE6_vtC3cz1EicBGBgGXIMrDBU521rGy0esuf90p_yvT5CXV0YrWCneUYoEj5tJB42Cjv_SliprXldRbrsCdb-8M1erLB4HaO2z1IXycUSWDR7BLYEK5YpnuQrRtCdn5DdfO5uV36Ys4I8DXHk2zghmH37wYO5NSUEhKe5uvAZbdGL0OXYjOVZFjHns8_tBnAPWowMReiSTZVtlpub_uh7ajKAmJknsjEQCAF4dG_mlyNtGCuMvIjt0FyABr7wfzf0B5J05CtpWNMhy2fbUTepF8Nn_f8qNXFGNs8ZTyPpoG8Wg"

That's a JWT you can visualize on https://jwt.io/

![image](https://user-images.githubusercontent.com/49282360/157471611-79afb5ff-edd5-485c-99cc-e9d85dd5e508.png)

**Comment by bibash28** [comment]
https://appdevtools.com/url-parser-query-string-splitter

https://talao.co/gaiax
