### ISSUE TITLE
problem with the date format of attributes

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/credible#205]
an attribute as birthDate causes a problem if it is not as the same format as VC W3C (expirationDate : "1991-12-10T12:02:55.268Z")
we would need to accept different date format for attributes as there is no standard for those types dates

**Comment by hawkbee1** [comment]
@ThierryThevenet Aujourd'hui le problème ne se pose que pour le selfIssued ou on doit pouvoir s'adapter à d'autre formats de date dans les credentials offers ?
