### ISSUE TITLE
IPFS link  -> ipfs://QmNwbEEupT7jR2zmrA87FsN4hUS8eXnCxM8DsL9RXc25cu",

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/credible#207]
At the moment  the path to an IPFS file is like 
"https://talao.mypinata.cloud/ipfs/QmNwbEEupT7jR2zmrA87FsN4hUS8eXnCxM8DsL9RXc25cu",

we would need to accept  ipfs://QmNwbEEupT7jR2zmrA87FsN4hUS8eXnCxM8DsL9RXc25cu and keep the gateway path as a parameter of the wallet.

**Comment by hawkbee1** [comment]
duplicate of #124
