### ISSUE TITLE
with did:web access to well_known

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/credible#217]
When issuer uses did:web, the makes several call to wellknown , it means that probably didkit is called several time_

try with https://talao/gaixpass

![Capture d’écran de 2022-03-08 17-59-06](https://user-images.githubusercontent.com/32768069/157287767-48bcabc0-16e0-481a-83b0-3da2b2b125fe.png)

**Comment by hawkbee1** [comment]
Right now: 17:10 I launch resolveDID('did:web:ecole42.talao.co', '{}') twice and result looks good
![image](https://user-images.githubusercontent.com/49282360/157483086-dbe05fd0-aadc-4656-963a-a87cb2a34e70.png)

You have multiple calls on the server ?

**Comment by ThierryThevenet** [comment]
yes.

NB : If the signature is verified as "failed" on the phone it is a didkit version issue. I have to upgrade the server
