### ISSUE TITLE
3/ Select credentials for SiopV2 presentation

### ISSUE THREAD

**Issue by hawkbee1** [TalaoDAO/credible#218]
1/ Build credential list with **jsonPath**
As a user I want to chose my credential in a list. The list of credential provided to user is filtered by claims analysis.
If a **credential type** was specified the list contains only credentials from this **credential type**
If a credential **issuer** was specified the list contains only credentials from this **issuer**

2/ Select a credential in the list
If the final list of credentials has only one element, this element is selected and we ask user to agree with presenting this credential.
If the list has more than one credential the list is displayed to user who pick the one he will present.
If the list of credentials is empty we provide the user with a link to a web page which will help user create a credential (link will be given later).

**Comment by ThierryThevenet** [comment]
This treatement module will be reused in other protocols.

**Comment by hawkbee1** [comment]
complexity: 3

**Comment by bibash28** [comment]
@hawkbee1 I think you have to provide the link here to direct when the credential is not available...
