### ISSUE TITLE
Did RSAKey Json User denial issue

### ISSUE THREAD

**Issue by bibash28** [TalaoDAO/credible#236]
After user denies twice... Nth happens after clicking.. I think we should navigate to setting page with instruction to enable

**Comment by TalebRafiepour** [comment]
@bibash28 
Can you explain more about it?

**Comment by bibash28** [comment]
Deny permission twice... and try to use the button...

**Comment by TalebRafiepour** [comment]
I got it

**Comment by hawkbee1** [comment]
short complexity; 1
