### ISSUE TITLE
enterprise wallet / General Information

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/credible#260]
One can remove

Blockckain / Tezos  and address and keep only DID

Website : Talao.io and email contact should be moved to another place (above didkit ???) in order to avoid confusion with the information about the enterprise itself

**Comment by hawkbee1** [comment]
To do:
- Remove website and contact email from General information page.
- If DID method is web: don't display the following field in General information page: blockchain, address and copy address button.
