### ISSUE TITLE
delay to collect a did:web VC

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/credible#262]
when you collect a VC with did:web example : https://talao.co/gaiax
The time to get and sign  the VC is about 10s, it would be great to have a spinner or a message to wait

**Comment by ThierryThevenet** [comment]
maybe best solution is to set the button inactive and display a message while the wallet is signing

**Comment by hawkbee1** [comment]
Looks like this behavior is specific to https://talao.co/gaiax and the web site displays OK message before the wallet does.
Nevertheless, this change is useful.
While the VC is accepted we display a popup with following text: Please wait a few seconds…
