### ISSUE TITLE
transfert self claim or did auth with credential offer

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/credible#294]

**Comment by ThierryThevenet** [comment]
cf https://github.com/TalaoDAO/talao-wallet/blob/dev-talao/docs/talao_interaction_protocol.md#wallet-implementation-to-be-done-for-scope-or-self-signed-vc

**Comment by ThierryThevenet** [comment]
did_auth est produit si le selfissued n existe pas. le did_auth est une fonction de didkit, il faut passer dans les options les nonce si il existe. le self issued est passé dans une presentation , il faut donc y mettre des options qui sont le nonce ("challenge) et le proofPurpose qui est "authentication" dans ce cas (didkit.dign_presentation(...)

**Comment by ThierryThevenet** [comment]
cf doc https://github.com/TalaoDAO/wallet-interaction/blob/main/README.md#issuer-implementation

**Comment by hawkbee1** [comment]
Dans credential offer, lors de l'acceptation il faut envoyer quelque chose de signé avec le DID.
=> Au minimum il faut fournir un DIDAuth.
=> Si output descriptior => envoyer verifiable presentation donnant les éléments. => DIDAuth est inutile dans ce cas... ou on ajoute.
