### ISSUE TITLE
Bouton pour recovery et reset dans le menu settings

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/credible#31]
Lorsque l on clic sur une de ces options il apparait une alerte qui demande la confirmation.
En anglais le bouton affiche "continue" sur 2 lignes
Idem en francais avec "Authoriser"
Une solution est de changer la phrase pour ne repondre que par Yes ou No...ou changer les boutons ?

**Comment by hawkbee1** [comment]
Change of buttons padding done for every buttons of the application.
