### ISSUE TITLE
Account creation ...

### ISSUE THREAD

**Issue by jdsika** [TalaoDAO/credible#338]
... does not show seed phrases to write them down.

**Comment by hawkbee1** [comment]
Old ticket :-/ 
No seed phrase, What do you mean ? That's for wallet account during onboarding or when you add another crypto account @jdsika ?

**Comment by jdsika** [comment]
I cannot remember... I assume it was during onboarding

**Comment by hawkbee1** [comment]
When new account is created the seed phrase is shown. If user import an account (private key, seed phrase), nothing is shown.
