### ISSUE TITLE
sur alert "Faites vous confiance à ce domaine ?"  

### ISSUE THREAD

**Issue by thierry-thevenet** [TalaoDAO/credible#4]
"Authoriser" est sur 2 lignes

**Comment by ThierryThevenet** [comment]
oui/non rentrera dans la case .....

**Comment by ThierryThevenet** [comment]
voir issue https://github.com/TalaoDAO/credible/issues/18

**Comment by ThierryThevenet** [comment]
actuellement le bouton affiche "Oui/Non" 
Il faudrait mettre "Oui" et remplacer "Refuser" par "Non"

**Comment by hawkbee1** [comment]
Oups... 2 cases différentes
