### ISSUE TITLE
Menu 'Settingds" 3 em menu

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/credible#7]
IL faut changer le nom et l'icon pour avoir "Settings" a la place de "profil" (en bas a droite).

prevoir un onglet : "information generale" en y mettant en particulie rles version de dikt, credible et de la wallet. Mettre le DID ici et prevoir de pouvoir copier le DID
personnel : ok
confidentialité et sécurité : ok
condition d'utilsiation : y mettre les CGU
recuperation : ok
ajouter un onglet : Reinitialiser le portefeuille avec une confirmation par bouton comme pouir "recuperation"
supprimer l'onglet support et notice (on verra plus tard)

**Comment by ThierryThevenet** [comment]
ajouter un menu Registry pour choisir le registre des issuer. cf Modification du protocole

**Comment by hawkbee1** [comment]
seul le menu de bas d'écran est fait pour l'instant
