### ISSUE TITLE
creer compte Talao pour les stores Apple et Google

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/credible#73]

**Comment by hawkbee1** [comment]
Pour google : https://support.google.com/googleplay/android-developer/answer/6112435?hl=en

**Comment by hawkbee1** [comment]
pour apple : https://idmsa.apple.com/IDMSWebAuth/signin.html?path=%2Fenroll%2F&appIdKey=891bd3417a7776362562d2197f89480a8547b108fd934911bcbea0110d07f757&rv=0
